version: '3.8'
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    image: item-composition-service:latest
    command: air -c cmd/.air.toml
    ports:
      - "3030:3030"
    volumes:
      - ./:/app
