version: '3.8'
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    image: item-composition-service:latest
    depends_on:
      - jaeger
    ports:
      - "3030:3030"
      - "8080:8080"
    volumes:
      - ./config/config.yaml:/etc/item-composition-service/config.yaml
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: unless-stopped
    ports:
      - "16686:16686" # jaeger Web UI
      - "4317:4317" # otel gRPC collector

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./deployment/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./deployment/dashboards:/var/lib/grafana/dashboards
      - ./deployment/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./deployment/grafana/datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yml
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
