version: '3.8'
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    image: item-composition-service:latest
    command: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
    ports:
      - "3030:3030"
    volumes:
      - ./:/app
