grpc_server:
  listen_address: :3030
  logging:
    disable: false
    disable_enrich_traces: false
    disable_log_request_message: false
    disable_log_response_message: false
    max_message_size: 1024
  start_deadline: 5s
  stop_deadline: 5s
  unix_socket_user: ""
logger:
  dev_mode: true
  elastic_config:
    flush_interval: 5s
    index: logs
    url: http://localhost:9200
    write_buffer_size: 1024
  encode_time: RFC3339TimeEncoder
  file_path: ./log/server.log
  log_level: debug
  transport: file+elastic
metrics:
  enable: true
  port: 8080
trace:
  batch_span_processor:
    batch_timeout: 5s
    export_timeout: 30s
    max_export_batch_size: 512
    max_queue_size: 2048
    with_blocking: false
  disable_baggage_propagation: false
  enabled: true
  url: localhost:4317
