grpc_server:
    listen_address: :8080
    logging:
        disable: false
        disable_enrich_traces: false
        disable_log_request_message: false
        disable_log_response_message: false
        max_message_size: 1024
    start_deadline: 5s
    stop_deadline: 5s
    unix_socket_user: ""
logger:
    dev_mode: true
    encode_time: RFC3339TimeEncoder
    file_path: log/server.log
    log_level: debug
    transport: stdout+file
