grpc_server:
    listen_address: :3030
    logging:
        disable: false
        disable_enrich_traces: false
        disable_log_request_message: false
        disable_log_response_message: false
        max_message_size: 1024
    start_deadline: 5s
    stop_deadline: 5s
    unix_socket_user: ""
local_storage:
    client_config_dir_path: /var/data/item-composition-service/client-configs
    client_spec_dir_path: /var/data/item-composition-service/client-specs
    logging:
        enabled: true
    template_dir_path: /var/data/item-composition-service/templates
logger:
    dev_mode: true
    elastic_config:
        flush_interval: 5s
        index: logs
        url: http://elasticsearch:9200
        write_buffer_size: 1024
    encode_time: RFC3339TimeEncoder
    file_path: /var/log/item-composition-service/server.log
    log_level: debug
    transport: file+elastic
metrics:
    enable: true
    port: 8080
mongo_storage:
    client_configs_collection: client_configs
    client_specs_collection: client_specs
    connection_timeout: 1s
    database: item_composition_service
    dsn: mongodb://localhost:27017
    enable: true
    heartbeat_frequency: 2s
    logging:
        enable: true
        query_max_bytes_to_log: 512
    max_pool_size: 1000
    operation_timeout: 2s
    read_preference: secondary
    templates_collection: templates
trace:
    batch_span_processor:
        batch_timeout: 5s
        export_timeout: 30s
        max_export_batch_size: 512
        max_queue_size: 2048
        with_blocking: false
    disable_baggage_propagation: false
    enabled: true
    url: jaeger:4317
